### PR TITLE
Add heroku deploy cron job

### LINKED ISSUE #22: Nightly redeploy with RGD main branch
This deployment regularly lags pretty far behind RGD dev. I'd like for it to stay up to date between releases

Can we change the depends to pull from RGD's main branch and have Heroku rebuild more frequently if not nightly?

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #22 by deploying from GitHub actions rather than Heroku's automatic deploys connected to GitHub

### CODE REVIEW

**Review by brianhelba — COMMENTED** [review]
The Heroku build cache may prevent this change from having much utility. The previously used version of upstream RGD will usually be installed by pip, as long as it meets the requirements specification of the downstream package.

**Comment by banesullivan** [comment]
Bummer... I was hoping that by using `pip`'s git protocol that the commit hash would be used somehow and prevent this... I really have no idea how any of that works under the hood.

Does Heroku's python build utility perform caching itself, or is it just saving the pip cache?

**Comment by banesullivan** [comment]
Perhaps here:

https://github.com/ResonantGeoData/RD-OpenGeo/blob/1c30fa3a80fb7054477329ab793435ba8e7f2ed7/requirements.txt#L3-L8

I need to specify a commit hash as well and have the CI update that hash in the cron job?

**Comment by banesullivan** [comment]
Closing and using dependabot with a regular release cycle from ResonantGeoData

**Pull request closed without merging**
